# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  endoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: ever_note_dev
  pool: 5
  username: ever_note
  password: 123456
  host: localhost
  port: 5432

  # bin/rails db:migrate RAILS_ENV=development